<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Reward Points Base for Magento 2
 */
/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\NewCategory */
?>
<div id="<?php /* @escapeNotVerified */ echo $block->getNameInLayout() ?>" style="display:none">
    <?php echo $block->getFormHtml();?>
    <?php echo $block->getAfterElementHtml();?>
</div>
