<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Reward Points Base for Magento 2
 */
/** @var \Amasty\Rewards\Block\Frontend\Catalog\HighlightProduct $block */
/** @var $escaper \Magento\Framework\Escaper */
?>
<div data-bind="scope: 'amasty-rewards-highlight-catalog'">
    <div class="amasty-rewards-loader" data-bind="visible: loader" style="display: none;">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Amasty_Rewards::images/ajax-loader.gif')); ?>"
             alt="<?= $escaper->escapeHtml(__('Ajax loader'))  ?>"/>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
            }
        }
    </script>
</div>
